/* =====================================================================
   과제 정의 — 대시보드가 읽는 유일한 출처
   oi 는 색상 키(A/B/C/all), owner 는 표시 이름
   mode: "joint" = 공동 과제 (체크박스 3개, 각자 자기 완료 표시)
         "solo"  = 개별 과제 (체크박스 1개, 담당자 본인)
   change / impact: 이 과제에서 확정/변경해야 할 것과, 그걸 정했을 때 무엇이
                     달라지는지 — 과제 상세(모달)에 표시된다.
   체크 상태는 이 파일이 아니라 analysis/progress.json 에 저장된다.

   ★ 2026-08-05: 결함 경계(People-Bean/Luryi-Suhir) 프레이밍을 폐기하고
   Stress Transfer Efficiency(STE) 프레이밍으로 전환하며 21개 과제 내용을
   전면 재작성. 과제 구조(개수·필드)는 그대로 유지. 자세한 경위는 README.md.
   ===================================================================== */
const PHASES = [
  { id:"P0", name:"공통 — FR 변수 확인 · 스윕 값/정규화 확정 · baseline 재현", week:"W1 · 8/03–8/09" },
  { id:"P1", name:"개별 추가 과제 · 1차원 단독 스윕",                week:"W2 · 8/10–8/16" },
  { id:"P2", name:"2차원 DoE 실행",                                  week:"W3 · 8/17–8/23" },
  { id:"P3", name:"병합 · 분석 · 발표",                              week:"W4 · 8/24–8/31" },
];

const TASKS = [
{ n:1, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"FR(리세스 깊이) 변수 SDE 추가 방법 확인", flag:"최우선·위험",
  purpose:"★2026-08-07 갱신: FR=15nm(0807.csv, G50_F15) 실제 Sentaurus 실행 완료 및 검증됨(유용성) — SVisual에서 baseline(FR=0)과 15nm 구조를 좌표축이 있는 단면(cutline, C2/C1)으로 직접 비교, TRECH 영역 세로 치수 차이가 약 0.015(=15nm)로 요청값과 일치함을 확인. baseline엔 남아있던 어깨 블록이 15nm 구조에서 그만큼 정확히 깎여 트렌치로 바뀐 것을 좌표로 확인했다 — 전기적 지표(IdSat_norm +12.9%, SSSat -32.9% 등)도 물리적으로 타당한 방향으로 변함. FR=0/FR=15nm 두 값에서 메쉬 생성 성공 + 단면이 의도한 리세스 형상과 일치 → done 조건 충족(유용성 기준). 나머지 2인의 개별 확인은 아직.",
  fixed:null, sweep:null,
  todo:["예제 스크립트에서 Esd 가 어떤 함수 호출(polyhedron 좌표 등)로 파라미터화됐는지 정확히 확인","같은 방식으로 FR 을 fin 바닥 아래 방향 좌표에 추가하는 문법을 실제 Sentaurus 에서 테스트","성공하면 Workbench 스윕 파라미터로 등록","SVisual 로 FR 값을 바꿔가며 형상이 의도대로 파이는지 확인 → Issue 에 단면 첨부","실패/막히면 즉시 팀 공유 — 지어내서 진행하지 말 것"],
  change:"baseline/finfet_sprocess.scm 의 TODO-FR 자리에 실제로 동작하는 코드가 채워진다.",
  impact:"성공하면 프로젝트 전체가 예정대로 진행 가능해진다. 실패하거나 오래 걸리면 격자 축을 재정의(예: 이미 있는 Esd 를 임시 Y축으로 대체)하는 안을 검토해야 한다 — 이 경우 README/PROMPT.md/ROLES.md 를 전부 다시 고쳐야 하므로 최대한 빨리 결론을 내야 한다.",
  done:["최소 2개 이상 서로 다른 FR 값에서 메쉬 생성 성공","SVisual 단면이 의도한 리세스 형상과 육안 일치"],
  out:["baseline/finfet_sprocess.scm (PR, 나머지 2명 승인)","단면 캡처"],
  warn:"8/07(금)까지 안 끝나면 즉시 팀 회의. 격자 축 재정의 안 검토." },

{ n:2, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"예제가 실공정 흐름인지 공정 에뮬레이션인지 확인",
  purpose:"SProcess 실제 공정 흐름이면 시간이 오래 걸리고 물리가 더 정확하다. 공정 에뮬레이션(SDE 로 형상만 근사 생성)이면 빠르다. FR 추가 문법(#1)이 어느 쪽 방식이어야 하는지가 이 결과에 따라 달라진다.",
  fixed:null, sweep:null,
  todo:["예제의 SDE/SProcess 파일이 deposit/etch 같은 공정 명령으로 구성됐는지, 아니면 직접 cuboid/polyhedron 으로 형상을 그리는지 확인","Workbench 프로젝트 트리에서 툴 흐름(SProcess→SDE→SDevice 인지, SDE→SDevice 인지) 확인"],
  change:"FR 을 어떤 방식(공정 명령 vs 직접 형상 편집)으로 넣을지가 이 결과에 따라 달라진다.",
  impact:"공정 에뮬레이션이면 #1 에서 시도한 polyhedron 좌표 편집 방식 그대로 진행 가능. 실공정 흐름이면 SProcess 커맨드 파일에 리세스 식각 단계를 추가하는 방식으로 #1 을 다시 시도해야 한다 — 이 경우 즉시 팀에 알릴 것.",
  done:["둘 중 하나로 확정, Issue 코멘트에 근거와 함께 기록"],
  out:["Issue 코멘트 (파일 제출 불필요)"] },

{ n:3, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"Ge%/FR 스윕 값 + STE 정규화 방법 확정", flag:"게이트",
  purpose:"★2026-08-06 갱신: Ge%/FR 스윕 값은 확정됨(x_levels=[30,40,50,60,70], y_levels=[0,10,20,30,35], values_confirmed:true) — 25격자점 본 스윕 시작 가능. STE 정규화 방법은 provisional 상태: 체적평균(현재 구현)과 계면 인접 단일점을 G50_F0에서 실측 비교하니 53.9% 차이(+ 한 성분 부호 반전)가 나와 지금 하나로 확정하지 않음 — 남은 24격자점 스윕에서 둘 다 뽑아 모은 뒤 최종 결정하기로 함.",
  fixed:null, sweep:null,
  todo:["#1 에서 확인한 FR 가능 범위(fin_height_nm=35nm 를 넘지 않는 현실적 범위) 산정","Ge% 는 공칭 50% 를 중심으로 대칭적인 스윕 범위 검토","격자 크기 결정 — 3인 체제이므로 x_levels 를 3의 배수로 잡으면 열 분할(ROLES.md 2절)이 깔끔하다","남다연의 STE 정규화 지점 후보(#8)를 놓고 팀 논의 → 채널 인접 지점 확정","응력을 GPa 로 환산하는 방법 확정","baseline/params.yaml 의 doe 섹션 + stress_transfer_efficiency.normalization 섹션을 확정값으로 채워 PR"],
  change:"x_levels, y_levels, values_confirmed, baseline_point, normalization.channel_adjacent_point, normalization.stress_to_GPa_method — 이 6개 필드를 확정값으로 채운다.",
  impact:"values_confirmed 가 true 로 바뀌고 normalization 이 채워지는 순간부터 build.py/contour.py 가 더 이상 경고를 띄우지 않고, 이후 모든 실행 결과가 '참고용'이 아니라 '확정 결론 후보'로 취급된다. 이 확정이 늦어지면 P1(1차원 스윕)을 시작할 수 없다.",
  done:["baseline/params.yaml doe 섹션 + normalization 섹션이 실제 값으로 채워짐, values_confirmed:true","나머지 2명 승인 PR 머지"],
  out:["baseline/params.yaml (PR, 나머지 2명 승인)"] },

{ n:4, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"baseline 구조 재현 (SDE)", flag:"위험",
  purpose:"★2026-08-06 갱신: finfet_sprocess.scm이 실제 원본 스크립트로 채워졌고, G50_F0(Strain_Impact=0/1) 조건에서 실제로 end-to-end 실행되어 검증 결과(IdSat_norm 등)가 나온 것까지 확인됨(유용성) — 구조 자체는 동작한다. 다만 3인이 각자 독립적으로 돌려 서로 값이 일치하는지 대조하는 건 아직(#5에서 별도 처리).",
  fixed:[["구조 출발점","Sentaurus FinFET_14nm 예제 (Munkang Choi, Synopsys, 2013)"]], sweep:null,
  todo:["예제의 SDE/SProcess 스크립트를 finfet_sprocess.scm 위치에 그대로 복사","#1 에서 검증된 TODO-FR 코드를 반영","TODO-STRESS-MESH: 계면(SiGe/Si) 국소 메쉬 정밀화 추가","SVisual 로 단면 캡처 → Issue 에 첨부"],
  change:"cuboid/재질/메쉬 정의를 예제 원본 문법에 맞춰 실제 채워 넣는다 (지금은 자리표시자).",
  impact:"이게 끝나야 어떤 시뮬레이션도 돌릴 수 있다. 여기서 막히면 프로젝트 전체 일정이 밀린다.",
  done:["에러 없이 메쉬 생성","단면이 의도한 리세스+에피 형상과 육안 일치","3인의 구조가 서로 같아 보인다"],
  out:["baseline/finfet_sprocess.scm (PR, 나머지 2명 승인)","단면 캡처"],
  warn:"8/07(목)까지 안 끝나면 즉시 팀 회의. 격자 크기를 더 줄이는 안 검토." },

{ n:5, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"공칭 격자점 실행 및 3인 대조", flag:"게이트",
  purpose:"W1 종료 게이트. 3명이 독립적으로 같은 조건(Ge% 50%, FR 기준값)을 돌려 같은 값이 나오는지 확인한다.",
  fixed:[["Run ID","#3 에서 확정된 baseline_point"]], sweep:null,
  todo:["finfet_sdevice.cmd 의 TODO-STRESS-PHYSICS 를 설치 버전 User Guide 로 확인","공칭 격자점 실행 → CSV 한 줄로 기록","3명의 stress_GPa/ste 를 Issue 코멘트에 나란히 정리"],
  change:"finfet_sdevice.cmd 의 응력 추출 설정을 실제로 확정한다 (지금은 TODO).",
  impact:"이 결과가 이후 확정된 격자 수 전부에 동일하게 적용될 물리 모델의 기준이 된다. 여기서 확정을 미루면 각자 다른 설정으로 스윕하게 되어 STE 지도가 오염된다.",
  done:["3명의 stress_GPa 가 서로(모든 쌍) 5% 이내","baseline/ 확정 PR 머지"],
  out:["runs/<이름>_baseline.csv","baseline/ 확정 PR"] },

{ n:6, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"분석 파이프라인 시험 (더미 데이터)", flag:"쉬움",
  purpose:"Sentaurus 결과를 기다리는 동안 build → contour 가 도는지 미리 확인.",
  fixed:null, sweep:null,
  todo:["pip install -r analysis/requirements.txt","python analysis/make_dummy_data.py","python analysis/build.py","python analysis/contour.py --all-figures","python analysis/make_dummy_data.py --clean  ← 반드시 삭제"],
  change:"없음 — 확인만 하는 과제.",
  impact:"여기서 에러가 나면 스크립트 버그를 지금 잡는 것이고, 넘어가면 실제 데이터가 나온 뒤에야 발견해서 더 큰 지연이 생긴다.",
  done:["contour.py 판정이 정상적으로 나온다 (더미에 교호작용을 심어둠)","analysis/figures/contour_ste.png 생성","더미를 지웠다 (runs/ 에 DUMMY 파일이 없다)"],
  out:["없음 (확인만)"] },

{ n:7, phase:"P1", oi:"A", owner:"유용성", mode:"solo", title:"Choi 2012 원 논문 응력 데이터 직접 확인 + STE 개념 재검증", flag:"선행·발표근거",
  purpose:"우리 방법론의 핵심 근거는 Choi 2012 논문 자신의 데이터(근접효과: nested 조건 −1289MPa vs isolated 조건 +53MPa)와 그 논문에 이미 등장하는 'Stress Transfer Efficiency' 라는 용어다. 이걸 원문에서 직접 확인하지 않은 채 발표하면 Q&A 에서 바로 흔들린다.",
  fixed:null, sweep:null,
  todo:["Choi et al. 2012 원문을 학교 도서관/저널 구독으로 직접 확보","nested/isolated 응력 수치(−1289MPa / +53MPa)를 원문 표·그림과 대조","'Stress Transfer Efficiency' 용어가 정확히 어떤 문맥·정의로 쓰였는지 확인 — 우리가 쓰려는 정의(StressEL/명목응력 비율)와 같은지 다른지 판단","결과를 docs/model_choice.md 에 정리"],
  change:"'이 방법론의 핵심 데이터적 근거가 정확한가'를 확정한다.",
  impact:"수치와 문맥이 확인되면 발표에서 'Choi 2012 자신의 데이터로 재구성했다'는 서사를 안전하게 인용할 수 있다. 대조 결과가 다르면(예: 용어 정의가 다르면) 발표에서 그 표현을 빼거나 우리 정의로 명확히 구분해서 말해야 한다. ★ 팀은 이 용어의 선행 사용에 대한 전면적인 특허/문헌 선점 조사는 하지 않기로 했다 — 이 과제는 그것과 별개로, 우리가 인용하는 숫자·문맥 자체가 정확한지만 확인하는 것이다.",
  done:["nested/isolated 수치 원문 대조 완료","'Stress Transfer Efficiency' 용어 사용 맥락 확인 및 우리 정의와의 이동(異同) 정리"],
  out:["docs/model_choice.md"] },

{ n:8, phase:"P1", oi:"C", owner:"남다연", mode:"solo", title:"메쉬 수렴성 검증 + STE 정규화 지점 후보 조사", flag:"선행·발표근거",
  purpose:"응력은 SiGe/Si 계면에 국소화된 현상이라 메쉬가 성기면 결과가 왜곡된다. 또한 STE 계산에 필요한 '채널 인접' 지점이 아직 정의되지 않았으므로, 메쉬 검증과 함께 후보 지점을 제안해 #3 확정 논의의 근거로 쓴다.",
  fixed:[["구조","공칭 격자점(#5 결과 구조 재사용)"]],
  sweep:{axis:"계면 국소 메쉬 밀도", base:"중간(baseline)", levels:["성김","중간(baseline)","촘촘"],
         runs:["baseline_mesh_coarse","baseline_mesh_base","baseline_mesh_fine"],
         file:"runs/남다연_메쉬수렴.csv",
         note:"격자에는 안 올라가는 비교 전용 실행."},
  todo:["finfet_sprocess.scm 의 TODO-STRESS-MESH 를 3단계로 바꿔 실행","각 조건의 노드 수와 실행 시간 기록","메쉬 밀도 vs 응력 수렴 그래프","'채널 인접'으로 볼 만한 후보 지점 2~3개(좌표 기준) 제안 → #3 확정 논의에 반영"],
  change:"필요시 메쉬 정밀도를 baseline 으로 승격하고, STE 정규화 지점 후보를 팀에 제공한다.",
  impact:"후보 지점 제안이 없으면 #3 에서 STE 정규화 지점을 팀이 근거 없이 정하게 된다 — 발표 Q&A에서 '왜 그 지점을 골랐나요'에 답할 수 없다.",
  done:["중간→촘촘에서 응력 변화가 5% 이내면 baseline 메쉬가 충분","후보 지점 2~3개가 좌표와 함께 제안됨"],
  out:["runs/남다연_메쉬수렴.csv","STE 정규화 지점 후보 제안서"] },

{ n:9, phase:"P1", oi:"B", owner:"주수빈", mode:"solo", title:"Sentaurus 버전/라이선스 옵션 확인", flag:"선행·발표근거",
  purpose:"StressEL 출력과 FR 추가(#1)에 필요한 SProcess/SDE/SDevice 모듈이 우리 학교 라이선스에 실제로 켜져 있지 않으면 못 쓴다. 이 간극을 먼저 막아야 다른 과제들이 헛수고가 안 된다.",
  fixed:null, sweep:null,
  todo:["학교 라이선스 서버에 연결된 Sentaurus 버전 확인 (버전 번호, 설치 경로)","라이선스 매니저(FLEXlm 등)에서 실제로 체크아웃 가능한 모듈 목록 확인 — SDE/SProcess/SDevice/SVisual 외에 Stress/Mechanical 관련 옵션이 별도 라이선스인지","결과를 docs/license_check.md 에 정리, #1(FR 추가)·#4(baseline 재현) 작업과 모순 없는지 대조"],
  change:"'우리가 실제로 쓸 수 있는 버전·모듈'의 범위를 확정한다.",
  impact:"여기서 문제(모듈 없음, 버전 차이로 문법 다름 등)가 발견되면 #1·#4 골격에 즉시 영향을 준다 — 팀 전체에 바로 알릴 것.",
  done:["설치 버전 확인됨","라이선스로 실제 사용 가능한 모듈 목록 확정"],
  out:["docs/license_check.md"] },

{ n:10, phase:"P1", oi:"B", owner:"주수빈", mode:"solo", title:"Ge% 단독 스윕 (낮은 열, FR 공칭 고정)", flag:"체크포인트",
  purpose:"8/16 체크포인트의 판단 근거. Ge% 의 STE 주효과가 미미하면 2차원 격자를 다 돌리기 전에 방향을 바꿔야 한다.",
  fixed:[["FR","공칭(#3 확정값)"],["담당 열","Ge% 낮은 1/3 (ROLES.md 2절)"]],
  sweep:{axis:"Ge 조성(%) — 낮은 열", base:"공칭 50%", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/주수빈_Ge스윕.csv"},
  todo:["#3 확정 즉시 시작","각 Ge% 실행 → CSV 에 누적","Ge% vs stress_GPa, Ge% vs ste 그래프"],
  change:"이 스윕 결과로 Ge% 축이 STE 에 어떤 영향을 주는지 감을 잡는다.",
  impact:"주효과가 유의미하면 W3 로 그대로 진행. 미미하면 스윕 범위를 넓히거나, FR 쪽이 지배 변수라는 가설로 전환해야 한다.",
  done:["전부 수렴","Ge% 범위 내에서 ste 변화가 유의미한가 판단 완료"],
  out:["runs/주수빈_Ge스윕.csv","1차원 그래프"] },

{ n:11, phase:"P1", oi:"C", owner:"남다연", mode:"solo", title:"Ge% 단독 스윕 (높은 열, FR 공칭 고정)", flag:"체크포인트",
  purpose:"#10 과 같은 목적, 담당 열(높은 1/3)만 다르다 — 두 사람의 결과를 합치면 Ge% 축 전체(낮은열+높은열)의 주효과를 판단할 수 있다.",
  fixed:[["FR","공칭(#3 확정값)"],["담당 열","Ge% 높은 1/3 (ROLES.md 2절)"]],
  sweep:{axis:"Ge 조성(%) — 높은 열", base:"공칭 50%", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/남다연_Ge스윕.csv"},
  todo:["#3 확정 즉시 시작","각 Ge% 실행 → CSV 에 누적","Ge% vs stress_GPa, Ge% vs ste 그래프"],
  change:"이 스윕 결과로 Ge% 축이 STE 에 어떤 영향을 주는지 감을 잡는다 (높은 열 쪽).",
  impact:"#10 과 합쳐서 8/16 체크포인트를 판단한다.",
  done:["전부 수렴","Ge% 범위 내에서 ste 변화가 유의미한가 판단 완료"],
  out:["runs/남다연_Ge스윕.csv","1차원 그래프"] },

{ n:12, phase:"P1", oi:"A", owner:"유용성", mode:"solo", title:"FR 단독 스윕 (공칭 Ge% 50%, 중간 열)",
  purpose:"FR(리세스 깊이)이 STE 에 미치는 영향을 1차원으로 먼저 확인한다. 중간 열(공칭 Ge% 50% 담당)이 이 축 전체를 대표해서 스윕한다. Gendron-Hansen 2015(SISPAD)는 'FR 10nm 이상에서 응력 최대'라고 원문에 명시했다 — 우리 STE 지표로도 비슷한 경향이 나오는지 확인.",
  fixed:[["Ge%","공칭 50%(#3 확정값)"],["담당 열","Ge% 중간 1/3 (ROLES.md 2절)"]],
  sweep:{axis:"FR(nm)", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/유용성_FR스윕.csv"},
  todo:["#1(FR 추가)·#3(스윕값 확정) 완료 즉시 시작","각 FR 실행 → CSV 에 누적","FR vs stress_GPa, FR vs ste 그래프","Gendron-Hansen 2015 의 'FR≥10nm 에서 응력 최대' 경향과 비교(결함 형성 여부는 그 논문 범위 밖이라는 것에 유의)"],
  change:"FR 축의 STE 거동(포화/최댓값 여부)을 확인한다.",
  impact:"비단조 거동이 확인되면 발표에서 문헌 결과를 우리 데이터로 재확인한 것으로 인용 가능. 단조 증가만 보이면 그 취지 문장은 빼야 한다.",
  done:["전부 수렴","FR vs ste 경향 판정 완료"],
  out:["runs/유용성_FR스윕.csv","1차원 그래프"] },

{ n:13, phase:"P2", oi:"B", owner:"주수빈", mode:"solo", title:"Ge% 낮은 1/3 열",
  purpose:"2차원 격자의 왼쪽 1/3. #3 에서 확정된 Ge% 레벨 중 낮은 1/3 을 담당.",
  fixed:[["담당 열","#3 확정 후 ROLES.md 에 명시"]],
  sweep:{axis:"FR x Ge%(낮은 1/3)", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/주수빈_G낮은열.csv",
         note:"공칭 격자점은 #5 결과를 그대로 복사해 넣어도 된다."},
  todo:["담당 열 전체 실행 → 누적 CSV","사진+메모(runs/attachments/<run_id>/)도 함께 제출","python analysis/build.py 로 확인","git add 후 push"],
  change:"없음 — #3·#4·#5 에서 확정된 것을 그대로 반복 실행.",
  impact:"이 열이 끝나야 STE 지도의 왼쪽 1/3 이 채워진다.",
  done:["build.py 가 담당 열 격자점 전부를 인식","경고 메시지 없음"], out:["runs/주수빈_G낮은열.csv","runs/attachments/<run_id>/ (열 개수만큼)"] },

{ n:14, phase:"P2", oi:"A", owner:"유용성", mode:"solo", title:"Ge% 중간 1/3 열",
  purpose:"2차원 격자의 가운데 1/3. 공칭 Ge% 50% 가 포함된 열이라 #5(공칭 격자점) 결과와 가장 직접 연결된다.",
  fixed:[["담당 열","#3 확정 후 ROLES.md 에 명시"]],
  sweep:{axis:"FR x Ge%(중간 1/3)", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/유용성_G중간열.csv",
         note:"공칭 격자점은 #5 결과를 그대로 복사해 넣어도 된다."},
  todo:["담당 열 전체 실행 → 누적 CSV","사진+메모도 함께 제출","python analysis/build.py 로 확인","git add 후 push"],
  change:"없음 — 반복 실행.",
  impact:"이 열이 끝나야 STE 지도의 가운데 1/3 이 채워진다. 양옆 열(주수빈/남다연)과 인접하므로 교차검증(#16)에서 두 번 관여한다.",
  done:["build.py 가 담당 열 격자점 전부를 인식"], out:["runs/유용성_G중간열.csv","runs/attachments/<run_id>/"] },

{ n:15, phase:"P2", oi:"C", owner:"남다연", mode:"solo", title:"Ge% 높은 1/3 열",
  purpose:"2차원 격자의 오른쪽 1/3.", fixed:[["담당 열","#3 확정 후 ROLES.md 에 명시"]],
  sweep:{axis:"FR x Ge%(높은 1/3)", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/남다연_G높은열.csv"},
  todo:["담당 열 전체 실행 → 누적 CSV","사진+메모도 함께 제출","push"],
  change:"없음 — 반복 실행.",
  impact:"이 열이 끝나야 STE 지도의 오른쪽 1/3 이 채워진다.",
  done:["build.py 가 담당 열 격자점 전부를 인식"], out:["runs/남다연_G높은열.csv","runs/attachments/<run_id>/"] },

{ n:16, phase:"P2", oi:"all", owner:"전원", mode:"joint", title:"교차검증 — 인접 열 경계 1점씩", flag:"필수",
  purpose:"3명의 환경이 실제로 동일한지 확인. 이걸 안 하면 STE 지도의 굴곡이 물리인지 환경차인지 구분할 수 없다. 열이 3개(낮은/중간/높은)라 인접한 쌍끼리만 경계를 맞대므로, 중간 열 담당인 유용성이 양쪽 다 교차검증한다.",
  fixed:[["주수빈 추가 실행","유용성 담당 열과의 경계 격자점 1개"],["유용성 추가 실행","주수빈 경계 1개 + 남다연 경계 1개 (2점)"],["남다연 추가 실행","유용성 담당 열과의 경계 격자점 1개"]],
  sweep:{axis:"교차검증", base:"인접 열 경계", levels:["주수빈 ↔ 유용성 경계 1점","유용성 ↔ 남다연 경계 1점"],
         file:"runs/<이름>_교차검증.csv",
         note:"같은 run_id 를 두 사람이 올리면 build.py 가 자동으로 편차를 계산해 알려준다."},
  todo:["각자 지정된 경계 지점을 추가 실행 → runs/<이름>_교차검증.csv","python analysis/build.py 실행 → 교차검증 섹션 확인"],
  change:"없음 — 인접 담당 열의 경계 격자점을 그대로 재실행.",
  impact:"편차가 5% 이내면 지금까지의 모든 데이터를 신뢰하고 넘어간다. 초과하면 STE 지도 작성 전에 반드시 원인(버전/정규화 방식/모델 파라미터)을 규명해야 한다.",
  done:["편차 5% 이내 (주수빈↔유용성, 유용성↔남다연 두 쌍 모두)","초과 시 원인 규명 전까지 지도를 그리지 않는다"],
  out:["파일 제출은 위 CSV 로 충분 (별도 첨부 불필요)"] },

{ n:17, phase:"P3", oi:"A", owner:"유용성", mode:"solo", title:"Ge%×FR Stress Transfer Efficiency 2차원 지도", flag:"발표핵심",
  purpose:"발표의 시각적 하이라이트. '1차원 그래프 두 개'가 아니라 'Ge%×FR 2차원 STE 지도' 하나가 이 프로젝트의 결과물이다.",
  fixed:null, sweep:null,
  todo:["python analysis/build.py — 격자 100% 확인","python analysis/contour.py --all-figures","STE 가 Ge%·FR 각각에 독립적으로 반응하는지, 상호작용이 있는지 판정","발표용 축 라벨·폰트 크기 조정"],
  change:"없음 — 이미 확정된 데이터를 그림으로 만드는 과제.",
  impact:"이 그림 하나가 'Stress Transfer Efficiency 지도'라는 프로젝트 전체의 결과물을 요약한다 — 발표 점수에 직결된다.",
  done:["analysis/figures/contour_ste.png 생성","전체 격자점이 점으로 표시됨"],
  out:["analysis/figures/contour_ste.png"] },

{ n:18, phase:"P3", oi:"C", owner:"남다연", mode:"solo", title:"교호작용 회귀 + STE 시너지/트레이드오프 정량화 + 설계 맵", flag:"발표핵심·독창성",
  purpose:"지도가 휘었는지를 눈이 아니라 숫자로 판정하고, '설계 맵' 형태의 결과물을 만든다.",
  fixed:null, sweep:null,
  todo:["contour.py 회귀 출력 확보","교호작용항의 t값/p값/주효과 대비 크기 정리","'Ge% 가 G 일 때 STE 가 최대인 FR 은 X' 형태의 표 작성","STE 가 가장 높은 (Ge%, FR) 조합을 '최적 조합 후보'로 제시 — 확정 결론이 아니라 데이터 기반 후보임을 명시"],
  change:"없음 — 확정된 데이터에 대한 통계·정리 작업.",
  impact:"결론 문장(README.md/발표자료)의 빈칸이 여기서 채워진다: 'Ge% 와 FR 은 [독립적이지 않으며/독립적이며], STE 관점에서 [X] 조합이 가장 효율적이다.'",
  done:["결론 문장의 빈칸이 전부 채워짐","설계 맵 표 + 지도 완성"],
  out:["회귀 표","시너지 표","설계 맵 표","결론 문장"] },

{ n:19, phase:"P3", oi:"B", owner:"주수빈", mode:"solo", title:"발표자료 스토리라인 초안 — 조사과제·결과 통합", flag:"발표핵심",
  purpose:"#7~#9(Choi 2012 대조/메쉬·정규화/라이선스 조사)와 #17~#18(STE 지도/회귀)이 각자 따로 만든 결과물이라, 발표 전에 누군가는 이걸 하나의 서사로 엮어야 한다.",
  fixed:null, sweep:null,
  todo:["#7·#8·#9 조사 결과를 '방법론을 왜 이렇게 짰는가(결함 경계 → STE 전환 경위 포함)' 섹션으로 요약","#17 STE 지도와 #18 설계 맵/결론 문장을 '무엇을 발견했는가' 섹션으로 배치","서사 순서 초안 작성 (문제 제기 → 방법 → 결과 → 결론·한계)","#20(한계·향후과제) 초안 항목 취합"],
  change:"없음 — 이미 나온 결과물들의 배치·순서를 정하는 과제.",
  impact:"발표자료(#21) 제작 시간을 줄이고, 세 사람이 각자 만든 조각이 서로 다른 이야기를 하지 않도록 미리 맞춘다.",
  done:["슬라이드 목차(섹션별 어떤 결과물이 들어가는지) 초안 완성","#17·#18 담당자 둘의 리뷰를 받음"],
  out:["발표자료 스토리라인 초안 (슬라이드 목차)"] },

{ n:20, phase:"P3", oi:"all", owner:"전원", mode:"joint", title:"한계·향후 과제 정리",
  purpose:"한계를 정직하게 밝히는 것은 감점이 아니라 신뢰도 가점 요인이다.",
  fixed:null, sweep:null,
  todo:["'Stress Transfer Efficiency' 용어가 Choi 2012 에 이미 등장하며, 팀이 선행 사용 여부를 전면 검증하지 않기로 했다는 것을 명시","STE 정규화 방법(채널 인접 지점, GPa 환산)이 팀의 판단에 근거한 것이며 유일한 정답은 아니라는 것 명시","FR 이 예제에 없던 신규 변수라 검증 정도가 Ge% 축보다 낮다는 것 명시","순수 구조/응력 시뮬레이션이라 전기적 측정(Id-Vg 등)으로 교차검증하지 않았다는 것 명시","격자 해상도의 한계","공정 산포(통계적 변동성) 미고려"],
  change:"없음 — 지금까지 나온 미확인/한계 항목을 모아 정리.",
  impact:"발표 Q&A 에서 나올 질문에 선제 대응.",
  done:["5개 이상 항목이 발표자료에 명시됨"], out:["한계 슬라이드"] },

{ n:21, phase:"P3", oi:"all", owner:"전원", mode:"joint", title:"발표자료 작성",
  purpose:"10분 발표. 서사는 '이미 산업 표준인 공정 위에서 무엇을 새로 봤는가 → 무엇을 발견했나'.",
  fixed:[["문제 제기","20%"],["기존 접근 (정직한 인용)","15%"],["우리 질문","10%"],["방법 (+3인 교차검증)","15%"],["결과 (STE 지도)","30%"],["결론·한계","10%"]], sweep:null,
  todo:["#19 스토리라인 초안대로 슬라이드 배치","예상 질문 답변 준비"],
  change:"없음.",
  impact:"—",
  done:["'이거 그냥 Choi 2012 재탕 아닌가요?' → #7 결과로 답, FR 이라는 새 변수를 추가해 2차원으로 확장했다는 점 강조","'FR 은 왜 새로 넣었나요?' → #1·#2 결과로 답","'STE 정규화 방법의 근거는?' → #3·#8 결과로 답, 팀 판단임을 정직하게 인정","'메쉬는 충분한가요?' → #8 결과로 답","'3명 결과가 같다는 보장?' → #16 교차검증으로 답","'\"Stress Transfer Efficiency\" 라는 용어, 원래 있던 거 아닌가요?' → #7·#20 결과로 정직하게 답 (선행 사용 확인, 전면 검증은 안 했다는 것 인정)"],
  out:["발표자료"] },
];
