/* =====================================================================
   과제 정의 — 대시보드가 읽는 유일한 출처
   oi 는 색상 키(A/B/C/all), owner 는 표시 이름
   mode: "joint" = 공동 과제 (체크박스 3개, 각자 자기 완료 표시)
         "solo"  = 개별 과제 (체크박스 1개, 담당자 본인)
   change / impact: 이 과제에서 확정/변경해야 할 것과, 그걸 정했을 때 무엇이
                     달라지는지 — 과제 상세(모달)에 표시된다.
   체크 상태는 이 파일이 아니라 analysis/progress.json 에 저장된다.
   ===================================================================== */
const PHASES = [
  { id:"P0", name:"공통 — 예제 확인 · 스윕 값 확정 · baseline 재현", week:"W1 · 8/03–8/09" },
  { id:"P1", name:"개별 추가 과제 · 1차원 단독 스윕",                week:"W2 · 8/10–8/16" },
  { id:"P2", name:"2차원 DoE 실행",                                  week:"W3 · 8/17–8/23" },
  { id:"P3", name:"병합 · 분석 · 발표",                              week:"W4 · 8/24–8/31" },
];

const TASKS = [
{ n:1, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"FinFET_14nm/22nm 예제 실제 치수 확인", flag:"최우선·위험",
  purpose:"이 예제가 Intel 22nm Tri-Gate / PTM 14nm 에 대응한다는 건 지금 파일명 기반 추측일 뿐이다. BCAT 프로젝트에서 구조 코너를 직관으로 잘못 판단해 방향을 크게 틀었던 사건과 똑같은 패턴 — 반드시 실제 문서를 열어 대조한다.",
  fixed:null, sweep:null,
  todo:["Sentaurus Applications Library 에서 FinFET_14nm, FinFET_22nm 예제 폴더 둘 다 연다","각 예제 안의 스펙 문서(치수·공정 조건)를 확인한다","Intel 22nm Tri-Gate 공개 자료(예: PMC5313396 논문)의 치수와 대조한다","PTM 14nm 모델 카드와 FinFET_14nm 예제 치수를 대조한다","일치/불일치 여부를 Issue 코멘트로 표로 정리한다"],
  change:"두 예제가 실제로 무엇에 대응하는지(또는 아무 것에도 대응하지 않는 그냥 일반 예제인지) 확정해야 한다.",
  impact:"대응이 확인되면 baseline 을 그 실제 공정 세대의 문헌값과 직접 비교할 수 있어 발표에서 설득력이 커진다. 대응이 안 되거나 미확인 상태로 남으면, README/발표자료에서 '문헌 재현'이 아니라 '가상 구조 기반 트레이드오프 연구'로 프레이밍을 낮춰야 한다 — 이게 독창성 주장(technical-notes.md 2-3절)에도 영향을 준다.",
  done:["FinFET_14nm/22nm 예제의 치수 스펙이 문서로 확보됨","Intel/PTM 대응 여부에 대한 명확한 결론(맞음/틀림/확인불가)"],
  out:["Issue 코멘트 (파일 제출 불필요)"] },

{ n:2, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"예제가 실공정 흐름인지 공정 에뮬레이션인지 확인",
  purpose:"SProcess 실제 공정 흐름이면 시간이 오래 걸리고 물리가 더 정확하다. 공정 에뮬레이션(SDE 로 형상만 근사 생성)이면 빠르지만 리세스+에피 삽입이 다른 방식으로 필요할 수 있다.",
  fixed:null, sweep:null,
  todo:["예제의 SDE/SProcess 파일이 deposit/etch 같은 공정 명령으로 구성됐는지, 아니면 직접 cuboid/polyhedron 으로 형상을 그리는지 확인","Workbench 프로젝트 트리에서 툴 흐름(SProcess→SDE→SDevice 인지, SDE→SDevice 인지) 확인"],
  change:"리세스+SiGe 에피 단계를 finfet_sde.scm(TODO-RECESS/TODO-EPI)에 어떤 방식(공정 명령 vs 직접 형상 편집)으로 넣을지가 이 결과에 따라 달라진다.",
  impact:"공정 에뮬레이션이면 지금 짜둔 finfet_sde.scm TODO 골격 그대로 진행 가능. 실공정 흐름이면 finfet_sde.scm 대신 SProcess 커맨드 파일에 리세스 식각+에피 증착을 추가하는 방식으로 골격을 다시 짜야 한다 — 이 경우 즉시 팀에 알릴 것.",
  done:["둘 중 하나로 확정, Issue 코멘트에 근거와 함께 기록"],
  out:["Issue 코멘트 (파일 제출 불필요)"] },

{ n:3, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"Ge% / 리세스 깊이 스윕 값 확정", flag:"게이트",
  purpose:"baseline/params.yaml 의 doe.x_levels/y_levels 는 지금 placeholder(예시)다. #1 에서 확인한 실제 fin 치수를 바탕으로, 기하학적으로 말이 되는 범위로 재확정해야 이후 모든 과제가 의미를 가진다.",
  fixed:null, sweep:null,
  todo:["#1 에서 확인한 fin 폭·fin 높이 기준으로 리세스 깊이가 fin 높이를 넘지 않는 현실적 범위 산정","People-Bean 근사식(Tc≈1.23x⁻³·⁰⁸)으로 각 Ge% 후보의 임계두께를 미리 계산해, 스윕 범위가 '전부 안전' 또는 '전부 결함'으로 쏠리지 않는지 확인","격자 크기(몇×몇) 결정 — 3인 체제이므로 x_levels 를 3의 배수로 잡으면 열 분할(2절)이 깔끔하다. 참고로 BCAT 때는 5×5=25점(3인)이었다","baseline/params.yaml 의 x_levels/y_levels/values_confirmed:true 로 PR"],
  change:"x_levels, y_levels, values_confirmed, baseline_point 4개 필드를 확정값으로 채운다.",
  impact:"values_confirmed 가 true 로 바뀌는 순간부터 build.py/contour.py 가 더 이상 경고를 띄우지 않고, 이후 모든 실행 결과가 '참고용'이 아니라 '확정 결론 후보'로 취급된다. 이 확정이 늦어지면 P1(1차원 스윕)을 시작할 수 없다.",
  done:["baseline/params.yaml doe 섹션이 실제 값으로 채워짐, values_confirmed:true","나머지 2명 승인 PR 머지"],
  out:["baseline/params.yaml (PR, 나머지 2명 승인)"] },

{ n:4, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"baseline 구조 재현 (SDE)", flag:"위험",
  purpose:"baseline/finfet_sde.scm 의 TODO 지점을 채워 실제로 도는 구조 스크립트를 만든다.",
  fixed:[["구조 출발점","FinFET_14nm 또는 FinFET_22nm 예제 (#1 결과로 결정)"]], sweep:null,
  todo:["예제의 SDE 스크립트를 finfet_sde.scm 위치에 그대로 복사","TODO-RECESS: S/D 영역을 리세스 형상으로 수정","TODO-EPI: 리세스에 SiGe 재질(Ge 조성 변수 포함) 채우기 — 재질 지정 문법은 User Guide 확인","TODO-STRESS-MESH: 계면 국소 메쉬 정밀화 추가","SVisual 로 단면 캡처 → Issue 에 첨부"],
  change:"cuboid/재질/메쉬 정의를 예제 원본 문법에 맞춰 실제 채워 넣는다 (지금은 자리표시자).",
  impact:"이게 끝나야 어떤 시뮬레이션도 돌릴 수 있다. 여기서 막히면 프로젝트 전체 일정이 밀린다.",
  done:["에러 없이 메쉬 생성","단면이 의도한 리세스+에피 형상과 육안 일치","3인의 구조가 서로 같아 보인다"],
  out:["baseline/finfet_sde.scm (PR, 나머지 2명 승인)","단면 캡처"],
  warn:"8/07(목)까지 안 끝나면 즉시 팀 회의. 격자 크기를 더 줄이는 안 검토." },

{ n:5, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"공칭 격자점 실행 및 3인 대조", flag:"게이트",
  purpose:"W1 종료 게이트. 3명이 독립적으로 같은 조건을 돌려 같은 값이 나오는지 확인한다.",
  fixed:[["Run ID","#3 에서 확정된 baseline_point"]], sweep:null,
  todo:["finfet_sdevice.cmd 의 TODO-STRESS-PHYSICS 를 설치 버전 User Guide 로 확인","공칭 격자점 실행 → CSV 한 줄로 기록","3명의 stress_GPa/mobility_gain_pct 를 Issue 코멘트에 나란히 정리"],
  change:"finfet_sdevice.cmd 의 Stress 물리 모델 설정을 실제로 확정한다 (지금은 TODO).",
  impact:"이 결과가 이후 확정된 격자 수 전부에 동일하게 적용될 물리 모델의 기준이 된다. 여기서 확정을 미루면 각자 다른 모델로 스윕하게 되어 등고선이 오염된다.",
  done:["3명의 stress_GPa 가 서로(모든 쌍) 5% 이내","baseline/ 확정 PR 머지"],
  out:["runs/<이름>_baseline.csv","baseline/ 확정 PR"] },

{ n:6, phase:"P0", oi:"all", owner:"전원", mode:"joint", title:"분석 파이프라인 시험 (더미 데이터)", flag:"쉬움",
  purpose:"Sentaurus 결과를 기다리는 동안 build → contour 가 도는지 미리 확인.",
  fixed:null, sweep:null,
  todo:["pip install -r analysis/requirements.txt","python analysis/make_dummy_data.py","python analysis/build.py","python analysis/contour.py --all-figures","python analysis/make_dummy_data.py --clean  ← 반드시 삭제"],
  change:"없음 — 확인만 하는 과제.",
  impact:"여기서 에러가 나면 스크립트 버그를 지금 잡는 것이고, 넘어가면 실제 데이터가 나온 뒤에야 발견해서 더 큰 지연이 생긴다.",
  done:["contour.py 판정이 '(b) 시너지' 로 나온다 (더미에 교호작용을 심어둠)","analysis/figures/contour_stress_GPa.png 생성","더미를 지웠다 (runs/ 에 DUMMY 파일이 없다)"],
  out:["없음 (확인만)"] },

{ n:7, phase:"P1", oi:"A", owner:"유용성", mode:"solo", title:"소성완화 모델 확인 + People-Bean 근사식 검증", flag:"선행·발표근거",
  purpose:"Sentaurus Stress 섹션에 전위결함 예측 모델이 있는지가 방법론 전체(하이브리드 vs 단일 시뮬레이션)를 결정한다. 발표 Q&A '결함을 왜 시뮬레이터가 아니라 별도 공식으로 처리하나요?' 의 답이기도 하다.",
  fixed:null,
  sweep:null,
  todo:["설치된 Sentaurus 버전의 Device User Guide 에서 Stress/Mechanical 관련 장 확인","소성 완화(전위결함 핵생성) 모델 존재 여부 결론","People-Bean(1985) 원 논문 PDF 를 학교 도서관/저널 구독으로 직접 구해 Fig.(임계두께 vs Ge 조성) 를 Tc≈1.23x⁻³·⁰⁸ 근사식과 대조 — ⚠ 검색으로는 페이월에 막혀서 못 구했음, 이 항목만 남음 (technical-notes.md 3-1절)","결과를 docs/model_choice.md 에 정리"],
  change:"'Sentaurus가 결함을 자동 반영하는가'라는 방법론의 전제를 확정한다.",
  impact:"모델이 있다고 확인되면 방법론을 단순화(경계선 오버레이 불필요)할 수 있다. 없다고 확인되면(현재 가정) 지금 설계된 하이브리드 방식(등고선+경계선 별도 오버레이)이 유일한 선택지임이 확정된다 — 이 경우 analysis/contour.py 는 그대로 쓴다.",
  done:["결론 문서화(있음/없음/확인불가)","People-Bean 근사식 오차 범위 기록 — ★ 이미 부분 완료: Hartmann et al., JAP 110, 083529 (2011) 실측 논문으로 'Ge≥22%에서 최대 ~2배 과소평가 경향' 확인됨(technical-notes.md 3-1절). 원 논문 그래프 직접 대조만 남음"],
  out:["docs/model_choice.md","docs/technical-notes.md 3-1절 (근사식 신뢰도 — 이미 작성됨)"] },

{ n:8, phase:"P1", oi:"C", owner:"남다연", mode:"solo", title:"메쉬 수렴성 검증 + fin 폭 확정", flag:"선행·발표근거",
  purpose:"응력은 SiGe/Si 계면에 국소화된 현상이라 메쉬가 성기면 결과가 왜곡된다. 또한 Luryi-Suhir 보정에 쓸 fin 폭이 확정돼야 경계선을 그릴 수 있다.",
  fixed:[["구조","공칭 격자점(#5 결과 구조 재사용)"]],
  sweep:{axis:"계면 국소 메쉬 밀도", base:"중간(baseline)", levels:["성김","중간(baseline)","촘촘"],
         runs:["baseline_mesh_coarse","baseline_mesh_base","baseline_mesh_fine"],
         file:"runs/남다연_메쉬수렴.csv",
         note:"격자에는 안 올라가는 비교 전용 실행."},
  todo:["finfet_sde.scm 의 TODO-STRESS-MESH 를 3단계로 바꿔 실행","각 조건의 노드 수와 실행 시간 기록","메쉬 밀도 vs 응력 수렴 그래프","FinFET_14nm/22nm 예제에서 실제 fin_width_nm 확인 → baseline/params.yaml PR"],
  change:"baseline/params.yaml 의 geometry.fin_width_nm (지금 PLACEHOLDER)을 확정하고, 필요시 메쉬 정밀도를 baseline 으로 승격한다.",
  impact:"fin_width_nm 이 확정돼야 contour.py 의 Luryi-Suhir 경계선(주황 점선)이 실제로 그려진다 — 지금은 이 값이 없어서 그 선이 아예 생략된다. 메쉬가 부족한 것으로 나오면 baseline 을 촘촘으로 올리는 PR 이 필요하고, 그 경우 #13·#15 는 재실행해야 한다.",
  done:["중간→촘촘에서 응력 변화가 5% 이내면 baseline 메쉬가 충분","fin_width_nm 이 params.yaml 에 채워짐"],
  out:["runs/남다연_메쉬수렴.csv","baseline/params.yaml PR (fin_width_nm)"] },

{ n:9, phase:"P1", oi:"B", owner:"주수빈", mode:"solo", title:"Sentaurus 버전/라이선스 옵션 확인", flag:"선행·발표근거",
  purpose:"#7 에서 '소성완화 모델이 문서상 있다/없다'를 확인해도, 우리 학교 라이선스에 그 모듈이 실제로 켜져 있지 않으면 못 쓴다. 이 간극을 먼저 막아야 다른 과제들이 헛수고가 안 된다.",
  fixed:null, sweep:null,
  todo:["학교 라이선스 서버에 연결된 Sentaurus 버전 확인 (버전 번호, 설치 경로)","설치 버전의 Release Notes 에서 Stress/Mechanical 관련 신규/변경 기능 확인","라이선스 매니저(FLEXlm 등)에서 실제로 체크아웃 가능한 모듈 목록 확인 — SDE/SDevice/SVisual 외에 Stress 관련 옵션이 별도 라이선스인지","결과를 docs/license_check.md 에 정리, #7 결과와 모순 없는지 대조"],
  change:"'우리가 실제로 쓸 수 있는 버전·모듈'의 범위를 확정한다.",
  impact:"여기서 문제(모듈 없음, 버전 차이로 문법 다름 등)가 발견되면 #7·#8·finfet_sdevice.cmd 골격에 즉시 영향을 준다 — 팀 전체에 바로 알릴 것.",
  done:["설치 버전 확인됨","라이선스로 실제 사용 가능한 모듈 목록 확정","#7 결과와 대조 완료"],
  out:["docs/license_check.md"] },

{ n:10, phase:"P1", oi:"A", owner:"유용성", mode:"solo", title:"Ge% 단독 스윕 (낮은 열, 리세스 깊이 공칭 고정)", flag:"체크포인트",
  purpose:"8/16 체크포인트의 판단 근거. Ge% 의 응력/이동도 주효과가 미미하면 2차원 격자를 다 돌리기 전에 방향을 바꿔야 한다.",
  fixed:[["리세스 깊이","공칭(#3 확정값)"],["담당 열","Ge% 낮은 1/3 (2절)"]],
  sweep:{axis:"Ge 조성(%) — 낮은 열", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/유용성_Ge스윕.csv"},
  todo:["#3 확정 즉시 시작","각 Ge% 실행 → CSV 에 누적","Ge% vs stress_GPa, Ge% vs mobility_gain_pct 그래프","각 지점의 People-Bean 임계두께와 실제 리세스 깊이 비교 — 이미 초과한 지점이 있는지 확인"],
  change:"이 스윕 결과로 Ge% 축의 안전 범위(경계선 안쪽)가 어디까지인지 감을 잡는다.",
  impact:"주효과가 유의미하면 W3 로 그대로 진행. 미미하면 스윕 범위를 넓히거나(더 낮은/높은 Ge%), 리세스 깊이 쪽이 지배 변수라는 가설로 전환해야 한다.",
  done:["전부 수렴","Ge% 범위 내에서 stress_GPa 변화가 유의미한가 판단 완료"],
  out:["runs/유용성_Ge스윕.csv","1차원 그래프"] },

{ n:11, phase:"P1", oi:"C", owner:"남다연", mode:"solo", title:"Ge% 단독 스윕 (높은 열, 리세스 깊이 공칭 고정)", flag:"체크포인트",
  purpose:"#10 과 같은 목적, 담당 열(높은 절반)만 다르다 — 두 사람의 결과를 합치면 Ge% 축 전체(낮은열+높은열)의 주효과를 판단할 수 있다.",
  fixed:[["리세스 깊이","공칭(#3 확정값)"],["담당 열","Ge% 높은 1/3 (2절)"]],
  sweep:{axis:"Ge 조성(%) — 높은 열", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/남다연_Ge스윕.csv"},
  todo:["#3 확정 즉시 시작","각 Ge% 실행 → CSV 에 누적","Ge% vs stress_GPa, Ge% vs mobility_gain_pct 그래프","각 지점의 People-Bean 임계두께와 실제 리세스 깊이 비교"],
  change:"이 스윕 결과로 Ge% 축의 안전 범위가 어디까지인지 감을 잡는다 (높은 열 쪽).",
  impact:"#10 과 합쳐서 8/16 체크포인트를 판단한다. 특히 Ge% 가 높을수록 People-Bean 임계두께가 급격히 얇아지므로(Tc∝x⁻³·⁰⁸), 이 담당 열에서 결함 경계에 먼저 닿는 지점이 나올 가능성이 높다.",
  done:["전부 수렴","Ge% 범위 내에서 stress_GPa 변화가 유의미한가 판단 완료"],
  out:["runs/남다연_Ge스윕.csv","1차원 그래프"] },

{ n:12, phase:"P1", oi:"B", owner:"주수빈", mode:"solo", title:"리세스 깊이 단독 스윕 (공칭 Ge%, 중간 열)",
  purpose:"리세스 깊이의 응력 효과와, 임계두께를 넘는 지점부터 결함 경계에 진입하는 걸 1차원으로 먼저 확인한다. 중간 열(공칭 Ge% 에 가장 가까운 담당)이 이 축 전체를 대표해서 스윕한다.",
  fixed:[["Ge%","공칭(#3 확정값)"],["담당 열","Ge% 중간 1/3 (2절)"]],
  sweep:{axis:"리세스 깊이(nm)", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/주수빈_리세스스윕.csv"},
  todo:["#3 확정 즉시 시작","각 리세스 깊이 실행 → CSV 에 누적","리세스 깊이 vs stress_GPa 그래프에 People-Bean 임계두께 수직선 표시","임계두께를 넘는 지점부터 응력 증가가 둔화/포화되는지 확인 (문헌상 비단조 거동, technical-notes.md 2-4절)"],
  change:"리세스 깊이 축의 '무한정 좋아지지 않는' 자체 기하학적 최적점이 있는지 확인한다.",
  impact:"비단조 거동이 확인되면 발표에서 '적당한 오버필이 최대'라는 문헌 결과를 우리 데이터로 재확인한 것으로 인용 가능. 단조 증가만 보이면(포화 없음) 그 취지 문장은 빼야 한다.",
  done:["전부 수렴","리세스 깊이 vs stress_GPa 경향 판정 완료"],
  out:["runs/주수빈_리세스스윕.csv","1차원 그래프"] },

{ n:13, phase:"P2", oi:"A", owner:"유용성", mode:"solo", title:"Ge% 낮은 1/3 열",
  purpose:"2차원 격자의 왼쪽 1/3. #3 에서 확정된 Ge% 레벨 중 낮은 1/3 을 담당.",
  fixed:[["담당 열","#3 확정 후 ROLES.md 에 명시"]],
  sweep:{axis:"리세스 깊이 x Ge%(낮은 1/3)", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/유용성_G낮은열.csv",
         note:"공칭 격자점은 #5 결과를 그대로 복사해 넣어도 된다."},
  todo:["담당 열 전체 실행 → 누적 CSV","사진+메모(runs/attachments/<run_id>/)도 함께 제출","python analysis/build.py 로 확인","git add 후 push"],
  change:"없음 — #3·#4·#5 에서 확정된 것을 그대로 반복 실행.",
  impact:"이 열이 끝나야 등고선의 왼쪽 1/3 이 채워진다.",
  done:["build.py 가 담당 열 격자점 전부를 인식","경고 메시지 없음"], out:["runs/유용성_G낮은열.csv","runs/attachments/<run_id>/ (열 개수만큼)"] },

{ n:14, phase:"P2", oi:"B", owner:"주수빈", mode:"solo", title:"Ge% 중간 1/3 열",
  purpose:"2차원 격자의 가운데 1/3. 공칭 Ge% 가 포함된 열이라 #5(공칭 격자점) 결과와 가장 직접 연결된다.",
  fixed:[["담당 열","#3 확정 후 ROLES.md 에 명시"]],
  sweep:{axis:"리세스 깊이 x Ge%(중간 1/3)", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/주수빈_G중간열.csv",
         note:"공칭 격자점은 #5 결과를 그대로 복사해 넣어도 된다."},
  todo:["담당 열 전체 실행 → 누적 CSV","사진+메모도 함께 제출","python analysis/build.py 로 확인","git add 후 push"],
  change:"없음 — 반복 실행.",
  impact:"이 열이 끝나야 등고선의 가운데 1/3 이 채워진다. 양옆 열(유용성/남다연)과 인접하므로 교차검증(#16)에서 두 번 관여한다.",
  done:["build.py 가 담당 열 격자점 전부를 인식"], out:["runs/주수빈_G중간열.csv","runs/attachments/<run_id>/"] },

{ n:15, phase:"P2", oi:"C", owner:"남다연", mode:"solo", title:"Ge% 높은 1/3 열",
  purpose:"2차원 격자의 오른쪽 1/3.", fixed:[["담당 열","#3 확정 후 ROLES.md 에 명시"]],
  sweep:{axis:"리세스 깊이 x Ge%(높은 1/3)", base:"공칭", levels:["#3 확정 후 채움"],
         runs:["#3 확정 후 채움"], file:"runs/남다연_G높은열.csv"},
  todo:["담당 열 전체 실행 → 누적 CSV","사진+메모도 함께 제출","push"],
  change:"없음 — 반복 실행.",
  impact:"이 열이 끝나야 등고선의 오른쪽 1/3 이 채워진다. Ge% 가 높을수록 People-Bean 임계두께가 급격히 얇아지므로(Tc∝x⁻³·⁰⁸), 이 담당 열에서 경계선을 넘는 격자점이 가장 많이 나올 가능성이 높다 — 결과가 이상하면 우선 경계선 근처인지부터 확인할 것.",
  done:["build.py 가 담당 열 격자점 전부를 인식"], out:["runs/남다연_G높은열.csv","runs/attachments/<run_id>/"] },

{ n:16, phase:"P2", oi:"all", owner:"전원", mode:"joint", title:"교차검증 — 인접 열 경계 1점씩", flag:"필수",
  purpose:"3명의 환경이 실제로 동일한지 확인. 이걸 안 하면 등고선의 굴곡이 물리인지 환경차인지 구분할 수 없다. 열이 3개(낮은/중간/높은)라 인접한 쌍끼리만 경계를 맞대므로, 중간 열 담당인 주수빈이 양쪽 다 교차검증한다.",
  fixed:[["유용성 추가 실행","주수빈 담당 열과의 경계 격자점 1개"],["주수빈 추가 실행","유용성 경계 1개 + 남다연 경계 1개 (2점)"],["남다연 추가 실행","주수빈 담당 열과의 경계 격자점 1개"]],
  sweep:{axis:"교차검증", base:"인접 열 경계", levels:["유용성 ↔ 주수빈 경계 1점","주수빈 ↔ 남다연 경계 1점"],
         file:"runs/<이름>_교차검증.csv",
         note:"같은 run_id 를 두 사람이 올리면 build.py 가 자동으로 편차를 계산해 알려준다."},
  todo:["각자 지정된 경계 지점을 추가 실행 → runs/<이름>_교차검증.csv","python analysis/build.py 실행 → 교차검증 섹션 확인"],
  change:"없음 — 인접 담당 열의 경계 격자점을 그대로 재실행.",
  impact:"편차가 5% 이내면 지금까지의 모든 데이터를 신뢰하고 넘어간다. 초과하면 등고선 작성 전에 반드시 원인(버전/추출 위치 정의/모델 파라미터)을 규명해야 한다.",
  done:["편차 5% 이내 (유용성↔주수빈, 주수빈↔남다연 두 쌍 모두)","초과 시 원인 규명 전까지 등고선을 그리지 않는다"],
  out:["파일 제출은 위 CSV 로 충분 (별도 첨부 불필요)"] },

{ n:17, phase:"P3", oi:"A", owner:"유용성", mode:"solo", title:"응력/이동도 등고선 + 경계선 오버레이", flag:"발표핵심",
  purpose:"발표의 시각적 하이라이트. Sentaurus 결과(색 채워진 등고선)와 문헌 기반 결함 경계선(People-Bean/Luryi-Suhir)을 한 그림에 겹친다.",
  fixed:null, sweep:null,
  todo:["python analysis/build.py — 격자 100% 확인","python analysis/contour.py --all-figures","등고선이 (a)독립 / (b)시너지 / (c)트레이드오프 중 어느 패턴인지, 경계선 안쪽에서는 어느 패턴인지 따로 판정","발표용 축 라벨·폰트 크기 조정"],
  change:"없음 — 이미 확정된 데이터와 공식을 그림으로 만드는 과제.",
  impact:"이 그림 하나가 '결함 발생 경계 지도'라는 프로젝트 전체의 결과물을 요약한다 — technical-notes.md 2-3절의 독창성 주장이 이 그림에 얼마나 명확히 드러나는지가 발표 점수에 직결된다.",
  done:["contour_stress_GPa.png 에 경계선 2개(또는 fin_width_nm 미확정 시 1개)가 표시됨","전체 격자점이 점으로 표시됨"],
  out:["analysis/figures/contour_stress_GPa.png"] },

{ n:18, phase:"P3", oi:"C", owner:"남다연", mode:"solo", title:"교호작용 회귀 + 시너지 정량화 + 2차원 설계 맵", flag:"발표핵심·독창성",
  purpose:"등고선이 휘었는지를 눈이 아니라 숫자로 판정하고, 개별 논문에는 없는 '설계 맵' 형태의 결과물을 만든다.",
  fixed:null, sweep:null,
  todo:["contour.py 회귀 출력 확보","교호작용항의 t값/p값/주효과 대비 크기 정리","시너지 표(개별 최적화 합 vs 결합 최적화)","경계선 안쪽에서의 최댓값 지점을 '최적 조합'으로 제시 (경계선 밖 최댓값과 혼동하지 않게 표에 명시)","'Ge% 가 G 일 때 안전한 최대 리세스 깊이는 X' 형태의 표 작성"],
  change:"없음 — 확정된 데이터에 대한 통계·정리 작업.",
  impact:"결론 문장(README.md/발표자료)의 빈칸이 여기서 채워진다: 'Ge% 와 리세스 깊이는 [독립적이지 않으며/독립적이며], 결함 경계 안쪽에서 결합 설계 시 응력을 추가로 [X] GPa(이동도 [Y]%) 개선할 수 있다.'",
  done:["결론 문장의 빈칸이 전부 채워짐","설계 맵 표 + 오버레이 그림 완성"],
  out:["회귀 표","시너지 표","설계 맵 표","결론 문장"] },

{ n:19, phase:"P3", oi:"B", owner:"주수빈", mode:"solo", title:"발표자료 스토리라인 초안 — 조사과제·결과 통합", flag:"발표핵심",
  purpose:"#7~#9(모델/라이선스/메쉬 조사)와 #17~#18(등고선/회귀)이 각자 따로 만든 결과물이라, 발표 전에 누군가는 이걸 하나의 서사로 엮어야 한다. 두 분석 과제(#17/#18)를 직접 하지 않은 사람이 초안을 잡으면, 발표를 처음 듣는 심사위원 입장에서 이해가 되는지 더 잘 검증된다.",
  fixed:null, sweep:null,
  todo:["#7·#8·#9 조사 결과를 '방법론을 왜 이렇게 짰는가' 섹션으로 요약","#17 등고선 그림과 #18 설계 맵/결론 문장을 '무엇을 발견했는가' 섹션으로 배치","서사 순서 초안 작성 (문제 제기 → 방법 → 결과 → 결론·한계)","#20(한계·향후과제) 초안 항목 취합"],
  change:"없음 — 이미 나온 결과물들의 배치·순서를 정하는 과제.",
  impact:"발표자료(#21) 제작 시간을 줄이고, 세 사람이 각자 만든 조각이 서로 다른 이야기를 하지 않도록 미리 맞춘다.",
  done:["슬라이드 목차(섹션별 어떤 결과물이 들어가는지) 초안 완성","#17·#18 담당자 둘의 리뷰를 받음"],
  out:["발표자료 스토리라인 초안 (슬라이드 목차)"] },

{ n:20, phase:"P3", oi:"all", owner:"전원", mode:"joint", title:"한계·향후 과제 정리",
  purpose:"한계를 정직하게 밝히는 것은 감점이 아니라 신뢰도 가점 요인이다.",
  fixed:null, sweep:null,
  todo:["Sentaurus 가 소성완화(결함)를 직접 모델링하지 않는다는 것(하이브리드 방법론의 한계)을 명시","People-Bean/Luryi-Suhir 근사식 자체의 오차 범위(#7 결과) 명시","Sentaurus 라이선스 제약으로 못 쓴 옵션이 있었다면 명시 (#9 결과)","FinFET_14nm/22nm 예제와 실제 공정 노드의 대응 관계가 미검증(#1)이었다면 그 사실 명시","격자 해상도의 한계","공정 산포(통계적 변동성) 미고려"],
  change:"없음 — 지금까지 나온 미확인/한계 항목을 모아 정리.",
  impact:"발표 Q&A 에서 나올 질문에 선제 대응. technical-notes.md 에 이미 정리된 '미확인' 항목들을 그대로 재사용하면 된다.",
  done:["5개 이상 항목이 발표자료에 명시됨"], out:["한계 슬라이드"] },

{ n:21, phase:"P3", oi:"all", owner:"전원", mode:"joint", title:"발표자료 작성",
  purpose:"10분 발표. 서사는 '왜 이 조합인가 → 무엇을 발견했나'.",
  fixed:[["문제 제기","20%"],["기존 접근 (정직한 인용)","15%"],["우리 질문","10%"],["방법 (+3인 교차검증)","15%"],["결과 (등고선+경계선)","30%"],["결론·한계","10%"]], sweep:null,
  todo:["#19 스토리라인 초안대로 슬라이드 배치","예상 질문 답변 준비"],
  change:"없음.",
  impact:"—",
  done:["'이거 그냥 응력 최대화 아닌가요?' → 결과물이 결함 경계 지도라는 점, 응력 최댓값이 아니라 안전 영역 내 최댓값을 찾는다는 점","'FinFET_14nm/22nm 이 실제로 뭘 흉내낸 건가요?' → #1 결과로 답 (미검증이면 미검증이라고 정직하게 답)","'Sentaurus 가 결함을 직접 계산하나요?' → #7·#9 결과로 답","'메쉬는 충분한가요?' → #8 결과로 답","'3명 결과가 같다는 보장?' → #16 교차검증으로 답"],
  out:["발표자료"] },
];
