/* =====================================================================
   과제 정의 — docs/ISSUES.md 와 같은 내용을 대시보드용으로 구조화한 것
   ★ 과제를 추가/수정하면 docs/ISSUES.md 도 함께 고칠 것
   ===================================================================== */
const PHASES = [
  { id: "P0", name: "공통 — 베이스라인 재현", week: "W1 · 8/03–8/09" },
  { id: "P1", name: "1차원 단독 스윕",        week: "W2 · 8/10–8/16" },
  { id: "P2", name: "2차원 DoE 실행",         week: "W3 · 8/17–8/23" },
  { id: "P3", name: "병합 · 분석 · 발표",     week: "W4 · 8/24–8/31" },
];

const TASKS = [
{ n:1, phase:"P0", owner:"전원", title:"베이스라인 논문 정독 및 파라미터표 확정",
  purpose:"baseline/params.yaml 의 빈 항목을 논문 원문에서 확인해 채운다. 이 값이 틀리면 이후 25개 격자점이 전부 무의미해진다.",
  fixed:[["출처","Kim et al., Micromachines 2022, 13(9), 1476"]],
  sweep:null,
  todo:["논문 정독 (오픈 액세스)","fin_width_nm / junction_depth_nm / channel_conc_cm3 / sd_peak_conc_cm3 를 params.yaml 에 기입","논문의 baseline Vth·SS·DIBL·Ion 을 Issue 코멘트에 표로 정리","3명이 읽은 값이 서로 같은지 대조"],
  done:["params.yaml 에 빈 항목이 없다","verified_by 에 이름이 적혀 있다","논문 값 표가 코멘트에 올라와 있다"],
  out:["baseline/params.yaml (PR)"] },

{ n:2, phase:"P0", owner:"전원", title:"학교 라이선스 예제 폴더 조사", flag:"최우선",
  purpose:"DRAM/BCAT/리세스 게이트 예제가 있으면 W1 일정이 통째로 단축된다. 다른 무엇보다 먼저 한다.",
  fixed:null, sweep:null,
  todo:["Applications Library / examples 폴더 탐색","키워드: DRAM, BCAT, recess, saddle, buried, RCAT, cell transistor","3D MOSFET / SDE Scheme 예제도 목록화","설치된 Sentaurus 버전 확인해 코멘트"],
  done:["예제 유무에 대한 명확한 답 (경로 또는 '없음')","3명의 Sentaurus 버전이 기록됨 — 다르면 즉시 팀 논의"],
  out:["Issue 코멘트"] },

{ n:3, phase:"P0", owner:"전원", title:"BCAT 3D 구조 재현 (SDE)", flag:"위험",
  purpose:"baseline/bcat_sde.scm 의 TODO-GEOM 지점을 채워 실제로 도는 구조 스크립트를 만든다.",
  fixed:[["Lgate","20 nm"],["리세스 깊이","120 nm"],["게이트 산화막","5 nm"],["일함수","4.8 eV (W)"]],
  sweep:null,
  todo:["bcat_sde.scm 실행","TODO-GEOM 을 논문 Fig.1 단면과 대조하며 수정","새들핀 형상을 SVisual 로 확인","컨택 4개 정의 확인","겹침부 국소 메쉬가 실제로 조밀한지 확대 확인 ← GIDL 신뢰성의 핵심","단면 캡처를 Issue 에 드래그&드롭"],
  done:["에러 없이 메쉬 생성","단면이 논문 그림과 육안 일치","Lgate 20nm / 리세스 120nm 가 ±2nm 이내","3명의 구조가 서로 같아 보인다"],
  out:["baseline/bcat_sde.scm (PR, 2인 승인)","단면 캡처"],
  warn:"8/07(목)까지 안 끝나면 즉시 팀 회의. 격자를 3×3(9점)으로 줄이는 안 검토." },

{ n:4, phase:"P0", owner:"전원", title:"baseline 격자점 D36_N100 실행 및 3인 대조", flag:"게이트",
  purpose:"W1 종료 게이트. 3명이 독립적으로 같은 조건을 돌려 같은 값이 나오는지 확인한다. 여기서 안 맞으면 이후 등고선은 3명의 환경 차이를 그린 그림이 된다.",
  fixed:[["Run ID","D36_N100"],["BTBT 모델","NonlocalPath"],["Vd","0.1 / 1.0 V"],["Vg 스윕","-1.0 → +2.8 V, 0.05 V step"]],
  sweep:null,
  todo:["bcat_sdevice.cmd 의 TODO-MODEL 을 설치 버전 User Guide 로 확인","D36_N100 실행","plt2csv.py 로 idvg.csv 생성 — 데이터셋 이름을 팀에 공유","extract.py 로 지표 추출","BTBT on/off 비교 — 모델 끄고 한 번 더 돌려 Vg<0 구간 차이 확인","3명의 Vth/SS/GIDL 을 표로 나란히 정리"],
  done:["3명의 Vth 가 서로 5% 이내","Vth/SS/DIBL 이 논문과 같은 자릿수·경향","BTBT 켠 것과 끈 것의 Vg<0 전류가 명확히 다르다 (같으면 모델이 안 켜진 것)","baseline 확정 PR 머지"],
  out:["runs/D36_N100/","baseline/ 확정 PR"] },

{ n:5, phase:"P0", owner:"전원", title:"분석 파이프라인 시험 (더미 데이터)", flag:"쉬움",
  purpose:"Sentaurus 결과를 기다리는 동안 extract → merge → contour 가 도는지 미리 확인. 시뮬레이션이 다 끝난 뒤 스크립트가 안 돈다는 걸 알게 되는 상황을 막는다.",
  fixed:null, sweep:null,
  todo:["pip install -r analysis/requirements.txt","python analysis/make_dummy_data.py","python analysis/extract.py --all","python analysis/merge.py","python analysis/contour.py --all-figures","python analysis/make_dummy_data.py --clean  ← 반드시 삭제"],
  done:["contour.py 판정이 '(b) 시너지' 로 나온다 (더미에 시너지를 심어둠)","contour_I_GIDL_A_um.png 생성","더미를 지웠다 (runs/ 에 _template 만 남음)"],
  out:["없음 (확인만)"] },

{ n:6, phase:"P1", owner:"A", title:"DBCAT 단독 스윕 (도핑 N100 고정)", flag:"체크포인트",
  purpose:"8/16 체크포인트의 판단 근거. DBCAT 의 GIDL 주효과가 미미하면 2차원 격자를 다 돌리기 전에 방향을 바꿔야 한다.",
  fixed:[["도핑 배수","1.00 (baseline)"],["BTBT 모델","NonlocalPath"]],
  sweep:{axis:"DBCAT (질화막 두께)", base:"36 nm (공칭)", levels:["24 nm","30 nm","36 nm","42 nm","48 nm"],
         runs:["D24_N100","D30_N100","D36_N100","D42_N100","D48_N100"]},
  todo:["5개 격자점 실행 (D36_N100 은 Phase 0 결과 재사용 가능)","extract.py --all → merge.py","DBCAT vs log10(GIDL) 1차원 그래프 첨부","24 nm 극단값에서 구조 생성 실패 여부 확인"],
  done:["5점 전부 수렴","판단: DBCAT 24→48nm 에서 GIDL 이 0.3 dex(약 2배) 이상 변하는가?","  예 → W3 진행 / 아니오 → 범위를 20~60nm 로 확대 재시도, 그래도 미미하면 시나리오 B 전환"],
  out:["runs/D*_N100/ 5개","1차원 그래프"] },

{ n:7, phase:"P1", owner:"B", title:"접합 도핑 단독 스윕 (DBCAT D36 고정)",
  purpose:"도핑 저감의 GIDL 효과와 그 대가(Ion 손실)를 1차원으로 먼저 파악한다.",
  fixed:[["DBCAT","36 nm (공칭)"],["BTBT 모델","NonlocalPath"]],
  sweep:{axis:"S/D 접합 도핑 농도", base:"baseline sd_peak_conc_cm3 (×1.00)",
         levels:["×0.30","×0.50","×0.70","×0.85","×1.00"],
         runs:["D36_N030","D36_N050","D36_N070","D36_N085","D36_N100"],
         note:"절대값이 아니라 baseline 대비 배수로 지정한다. baseline 이 바뀌면 절대값 기준 과제는 전부 다시 써야 하기 때문."},
  todo:["5개 격자점 실행","도핑배수 vs log10(GIDL) 그래프","도핑배수 vs Ion 그래프 ← 저도핑의 대가가 여기서 보인다","×0.30 에서 Ion 손실률을 수치로 정리"],
  done:["5점 전부 수렴","GIDL 이 도핑 저감에 따라 단조 감소하는가 (아니면 접합 프로파일 정의 의심)","Ion 손실률 명시"],
  out:["runs/D36_N*/ 5개","GIDL·Ion 그래프"] },

{ n:8, phase:"P1", owner:"C", title:"BTBT 모델 3종 비교", flag:"발표근거",
  purpose:"발표 Q&A '왜 그 모델을 썼나요?'에 대한 답을 실험으로 만든다. 심사 완성도 30점에 직결.",
  fixed:[["구조","D36_N100"],["메쉬","baseline"]],
  sweep:{axis:"BTBT 모델", base:"NonlocalPath", levels:["NonlocalPath","Hurkx","Schenk"],
         runs:["D36_N100_nonlocal","D36_N100_hurkx","D36_N100_schenk"]},
  todo:["3종 각각 실행","세 Id-Vg 를 한 그래프에 겹쳐 그리기 (Vg<0 구간 확대)","Vg=-0.5V 에서의 GIDL 값 표 비교","모델별 수렴 난이도·실행 시간 기록","'우리는 X를 쓴다, 근거는 Y' 1페이지 → docs/model_choice.md"],
  done:["3종 비교 그래프","선택 모델과 근거 문서화","선택 결과를 bcat_sdevice.cmd 에 반영 (2인 승인 PR)"],
  out:["docs/model_choice.md","비교 그래프"] },

{ n:9, phase:"P1", owner:"C", title:"메쉬 수렴성 검증", flag:"발표근거",
  purpose:"'GIDL 은 겹침부에 극도로 국소화된 현상이라 메쉬가 성기면 결과가 왜곡된다'는 우려를 정량적으로 해소한다.",
  fixed:[["구조","D36_N100"],["BTBT 모델","NonlocalPath"]],
  sweep:{axis:"겹침부 국소 메쉬 밀도 (RS.Overlap)", base:"중간 (baseline)",
         levels:["성김","중간(baseline)","촘촘"],
         runs:["D36_N100_mesh_coarse","D36_N100_mesh_base","D36_N100_mesh_fine"]},
  todo:["bcat_sde.scm 의 RS.Overlap 을 3단계로 바꿔 실행","각 조건의 노드 수와 실행 시간 기록","메쉬 밀도 vs GIDL 수렴 그래프"],
  done:["중간→촘촘 변화가 5% 이내면 baseline 메쉬가 충분하다고 결론","5% 초과면 baseline 을 촘촘으로 올리는 PR (2인 승인) + 실행시간 증가분 보고"],
  out:["수렴 그래프","판정 결과"] },

{ n:10, phase:"P2", owner:"A", title:"D24 열 (5점)",
  purpose:"2차원 격자의 왼쪽 끝 열. 질화막이 가장 얇은 조건.",
  fixed:[["DBCAT","24 nm"]],
  sweep:{axis:"도핑 배수", base:"×1.00", levels:["×0.30","×0.50","×0.70","×0.85","×1.00"],
         runs:["D24_N030","D24_N050","D24_N070","D24_N085","D24_N100"],
         note:"D24_N100 은 과제 #6 결과 재사용 가능"},
  todo:["5점 실행 → extract.py → PR"],
  done:["5점 전부 metrics.csv 에 nan 없음","merge.py 진행률에 반영됨"], out:["runs/D24_N*/ 5개"] },

{ n:11, phase:"P2", owner:"A", title:"D30 열 (5점)",
  purpose:"2차원 격자 두 번째 열.", fixed:[["DBCAT","30 nm"]],
  sweep:{axis:"도핑 배수", base:"×1.00", levels:["×0.30","×0.50","×0.70","×0.85","×1.00"],
         runs:["D30_N030","D30_N050","D30_N070","D30_N085","D30_N100"]},
  todo:["5점 실행 → extract.py → PR"],
  done:["5점 전부 metrics.csv 에 nan 없음"], out:["runs/D30_N*/ 5개"] },

{ n:12, phase:"P2", owner:"B", title:"D36 열 (5점) — 공칭",
  purpose:"공칭 DBCAT 열. 논문 값과 직접 대조하는 기준선.", fixed:[["DBCAT","36 nm (공칭)"]],
  sweep:{axis:"도핑 배수", base:"×1.00", levels:["×0.30","×0.50","×0.70","×0.85","×1.00"],
         runs:["D36_N030","D36_N050","D36_N070","D36_N085","D36_N100"],
         note:"과제 #7 결과를 전부 재사용 가능"},
  todo:["5점 실행 (대부분 재사용)","논문 값과 직접 대조해 코멘트로 보고"],
  done:["5점 전부 확보","논문 대조 결과 코멘트"], out:["runs/D36_N*/ 5개","논문 대조표"] },

{ n:13, phase:"P2", owner:"B", title:"D42 열 (5점)",
  purpose:"2차원 격자 네 번째 열.", fixed:[["DBCAT","42 nm"]],
  sweep:{axis:"도핑 배수", base:"×1.00", levels:["×0.30","×0.50","×0.70","×0.85","×1.00"],
         runs:["D42_N030","D42_N050","D42_N070","D42_N085","D42_N100"]},
  todo:["5점 실행 → extract.py → PR"],
  done:["5점 전부 metrics.csv 에 nan 없음"], out:["runs/D42_N*/ 5개"] },

{ n:14, phase:"P2", owner:"C", title:"D48 열 (5점)",
  purpose:"질화막이 가장 두꺼운 조건. 게이트 에치백이 과하면 온전류가 급감할 수 있다.",
  fixed:[["DBCAT","48 nm"]],
  sweep:{axis:"도핑 배수", base:"×1.00", levels:["×0.30","×0.50","×0.70","×0.85","×1.00"],
         runs:["D48_N030","D48_N050","D48_N070","D48_N085","D48_N100"]},
  todo:["5점 실행","Ion 을 특히 주의해서 확인 — 급감하면 즉시 보고"],
  done:["5점 전부 metrics.csv 에 nan 없음","Ion 경향 코멘트"], out:["runs/D48_N*/ 5개"] },

{ n:15, phase:"P2", owner:"전원", title:"교차검증 3점", flag:"필수",
  purpose:"3명의 환경이 실제로 동일한지 확인. 이걸 안 하면 등고선의 굴곡이 물리인지 환경차인지 구분할 수 없다.",
  fixed:[["A 가 추가 실행","D36_N100 (B 와 대조)"],["B 가 추가 실행","D24_N100 (A 와 대조)"],["C 가 추가 실행","D42_N100 (B 와 대조)"]],
  sweep:null,
  todo:["각자 지정된 1점을 추가 실행 (runs/D36_N100_xcheckA 처럼 접미사)","python analysis/merge.py 실행 → 교차검증 섹션 확인","결과를 표로 정리"],
  done:["3쌍 모두 GIDL 편차 5% 이내","초과 시 원인 규명 전까지 등고선을 그리지 않는다. 버전/정규화 폭/모델 파라미터를 순서대로 대조"],
  out:["교차검증 표"] },

{ n:16, phase:"P3", owner:"A", title:"GIDL 2차원 등고선 — 헤드라인 그림", flag:"발표핵심",
  purpose:"발표의 시각적 하이라이트. 심사 발표 20점의 핵심.",
  fixed:null, sweep:null,
  todo:["python analysis/merge.py — 격자 100% 확인","python analysis/contour.py","등고선이 (a)독립 / (b)시너지 / (c)트레이드오프 중 어느 패턴인지 육안 판정","발표용 축 라벨·폰트 크기 조정"],
  done:["contour_I_GIDL_A_um.png 생성","25개 격자점이 전부 점으로 표시됨","육안 판정이 contour.py 회귀 판정과 일치 (불일치면 데이터 이상)"],
  out:["analysis/figures/contour_I_GIDL_A_um.png"] },

{ n:17, phase:"P3", owner:"B", title:"Ion/DIBL/SS 등고선 + 트레이드오프 그림",
  purpose:"'GIDL 을 줄인 대가가 얼마인가'를 보여준다. Ion 손실 없이 GIDL 만 줄었다면 그게 최고의 결과.",
  fixed:null, sweep:null,
  todo:["python analysis/contour.py --all-figures","가장 중요한 그림: x=GIDL 저감률, y=Ion 손실률, 점=25개 격자점","Pareto front 표시"],
  done:["트레이드오프 산점도 완성","'GIDL X% 저감 시 Ion 손실 Y%' 를 수치로 제시"],
  out:["트레이드오프 산점도","등고선 4종"] },

{ n:18, phase:"P3", owner:"C", title:"교호작용 회귀 및 시너지 정량화", flag:"발표핵심",
  purpose:"등고선이 휘었는지를 눈이 아니라 숫자로 판정한다. 이 차이가 우리 기여의 크기.",
  fixed:null, sweep:null,
  todo:["contour.py 회귀 출력 확보","교호작용항의 t값/p값/주효과 대비 크기 정리","시너지 표(개별 최적화 합 vs 결합 최적화)를 발표용으로","시나리오 A/B/C 중 어디인지 확정"],
  done:["결론 문장의 빈칸이 전부 채워짐: 'DBCAT 과 접합 도핑은 [독립적이지 않으며/독립적이며], 결합 설계 시 개별 최적화 대비 GIDL 을 추가로 [X]% 저감할 수 있다. [DBCAT=__nm, 도핑=×__] 영역이 최적임을 제시한다.'"],
  out:["회귀 표","시너지 표","결론 문장"] },

{ n:19, phase:"P3", owner:"C", title:"2차원 설계 맵 작성", flag:"독창성",
  purpose:"개별 논문에는 없는 형태의 결과물. 심사 독창성 30점의 실체.",
  fixed:null, sweep:null,
  todo:["'DBCAT 이 D 일 때 최적 접합 조건은 X' 형태의 표","각 DBCAT 값에 대해 GIDL 최소가 되는 도핑 배수 표기","그 최적선이 등고선 위에서 직선인지 휘었는지 표시 ← 휘었으면 트레이드오프의 시각적 증거"],
  done:["5개 DBCAT 값에 대한 최적 도핑 표 완성","최적선을 등고선 위에 오버레이"],
  out:["설계 맵 표","오버레이 그림"] },

{ n:20, phase:"P3", owner:"전원", title:"한계·향후 과제 정리",
  purpose:"한계를 정직하게 밝히는 것은 감점이 아니라 신뢰도 가점 요인이다.",
  fixed:null, sweep:null,
  todo:["통계적 변동성(공정 산포) 미고려 — 결정론적 최적화에 집중","3D 어레이 레벨 효과(인접 WL 간섭) 미고려","에치백 공정의 비평탄성 미반영","Row Hammer 는 문헌 기반 서술적 연결이며 직접 시뮬레이션 안 함","격자 해상도 5×5 의 한계"],
  done:["5개 항목이 발표자료에 명시됨"], out:["한계 슬라이드"] },

{ n:21, phase:"P3", owner:"전원", title:"발표자료 작성",
  purpose:"10분 발표. 서사는 '왜 이 조합인가 → 무엇을 발견했나'.",
  fixed:[["문제 제기","20%"],["기존 접근 (정직한 인용)","15%"],["우리 질문","10%"],["방법 (+3인 교차검증)","15%"],["결과 (2차원 등고선)","30%"],["결론·한계","10%"]],
  sweep:null,
  todo:["서사 구조대로 슬라이드 배치","예상 질문 7개 답변 준비"],
  done:["'이거 그냥 파라미터 최적화 아닌가요?' → 결과물이 2차원 상호작용 맵이라는 점","'DBCAT 을 실제 공정에서 제어 가능한가?' → 에치백 양으로 조절, 논문이 명시","'공정 산포는?' → 향후 과제로 명시 (무리하게 아는 척 안 함)","'왜 그 BTBT 모델?' → 과제 #8 결과로 답","'메쉬는 충분한가?' → 과제 #9 결과로 답","'3명 결과가 같다는 보장?' → 과제 #15 교차검증으로 답"],
  out:["발표자료"] },
];
